name: Continuous deployment (WASM Build)
on:
  workflow_run:
    branches: [ main ]
    workflows: [ Continuous integration ]
    types: [ completed ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          target: wasm32-unknown-unknown
      - name: Install wasm-pack ğŸ”§
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WebAssembly ğŸ—
        run: |
          sed -i "s/#wasm# //" Cargo.toml
          wasm-pack build --release --target web

      - name: Upload wasm dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wasm-dist
          path: ./pkg

      - name: Clean cache # Otherwise the cache is much too big.
        run: |
          du -hs target
          rm -rf target/*/incremental
          rm -rf target/*/*/*slint*
          du -hs target          

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Download wasm dist artifacts
        uses: actions/download-artifact@v3
        with:
          name: wasm-dist
          path: ./pkg

      - name: Copy index.html to pkg directory
        run: cp index.html ./pkg

      - name: Deploy to GH Pages ğŸš€
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: ./pkg
          keep_history: false
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}