name: Continuous deployment (WASM Build)
on:
  workflow_run:
    branches: [ main ]
    workflows: [ Continuous integration ]
    types: [ completed ]

permissions:
  contents: write

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ›ï¸
        uses: actions/checkout@v2

      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust
        with:
          target: wasm32-unknown-unknown

      - name: Install wasm-pack ğŸ”§
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WebAssembly ğŸ—
        run: |
          sed -i "s/#wasm# //" Cargo.toml
          wasm-pack build --release --target web

      - name: Copy index.html to pkg directory
        run: cp index.html ./pkg

      - name: Remove .gitignore from pkg directory
        run: rm -f ./pkg/.gitignore

      - name: Deploy to GitHub Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pkg/