name: Continuous deployment (WASM Build)
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install wasm-pack ğŸ”§
        run: cargo install wasm-pack

      - name: Build WebAssembly ğŸ—
        run: wasm-pack build --target web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Download wasm dist artifact
        uses: actions/download-artifact@v3
        with:
          path: ./pkg

      - name: Deploy to GH Pages ğŸš€
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./pkg
          keep_history: false
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}