name: Continuous deployment (WASM Build)
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install wasm-pack ğŸ”§
        run: cargo install wasm-pack

      - name: Build WebAssembl ğŸ—
        run: wasm-pack build --target web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Deploy to GH Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}