name: Continuous deployment (WASM Build)
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install wasm-pack ğŸ”§
        run: cargo install wasm-pack

      - name: Build WebAssembly ğŸ—
        run: |
          sed -i "s/#wasm# //" Cargo.toml
          wasm-pack build --release --target web

      - name: Upload wasm dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: wasm-dist   # <-- Choose any name you prefer
          path: ./pkg

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Download wasm dist artifact
        uses: actions/download-artifact@v3
        with:
          name: wasm-dist
          path: ./pkg

      - name: Deploy to GH Pages ğŸš€
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main
          build_dir: ./pkg
          keep_history: false
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}